mediaFields:
- id: exif_Components_configuration
  type: Text
  name:
    en-US: Components configuration
    sv-SE: Komponenter konfigurering
  settings:
    multiCulture: false
    administration:
      columns: true
      filter: true
      readonly: false
    storefront:
      visible: false
      searchable: false
